# Generated by Django 5.2 on 2026-04-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_otp_email_otp_user_otp_otp_user_id_6b614e_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup'), ('reset_password', 'Reset Password'), ('email_change', 'Email Change')], default='signup', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', max_length=20),
        ),
    ]
