# Generated by Django 5.2 on 2026-05-20 04:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat Amount')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='maximum_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='offer_name',
            field=models.CharField(default='Offer', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoffer',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat Amount')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoffer',
            name='maximum_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='offer_name',
            field=models.CharField(default='Offer', max_length=120),
            preserve_default=False,
        ),
    ]
