# Generated by Django 5.2 on 2026-05-12 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_return_rejectiion_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='return_rejectiion_reason',
            new_name='return_rejection_reason',
        ),
    ]
