# Generated by Django 5.2 on 2026-05-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='coupon_discount_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='final_item_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='offer_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='original_item_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
