# Generated by Django 5.2 on 2026-05-01 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_created_at_alter_category_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantimage',
            name='variant',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('color_code', models.CharField(blank=True, help_text='Optional hex code, example: #000000', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='products.product')),
            ],
            options={
                'db_table': 'color_variants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ColorVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='products/color_variants/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.colorvariant')),
            ],
            options={
                'db_table': 'color_variant_images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('size', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variants', to='products.colorvariant')),
            ],
            options={
                'db_table': 'size_variants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
        migrations.DeleteModel(
            name='VariantImage',
        ),
        migrations.AddConstraint(
            model_name='colorvariant',
            constraint=models.UniqueConstraint(fields=('product', 'color_name'), name='unique_color_per_product'),
        ),
        migrations.AddConstraint(
            model_name='sizevariant',
            constraint=models.UniqueConstraint(fields=('color_variant', 'size'), name='unique_size_per_color_variant'),
        ),
    ]
