# Generated by Django 5.2 on 2026-05-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
